### PR TITLE
fix: no longer add zeroes to rolls

### LINKED ISSUE #385: Remove +0 from dice roll strings
### New Feature or Changed Behaviour

Whenever the OSE system is putting together an array of dice terms to turn into a dice roll, do not push the dice term to the array if the value is `0`.

The changed behavior will be that the resulting strings will not have `+0` as any dice term

### Why?

It's impacting our ability to test issues with our dice rolls, because "d20 + 0" and "d20" might both be technically correct roll strings, but we can only easily assert 1 string, not every possible correct roll string.

It's also a bit of an eyesore

image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by anthonyronda**
Fixes #385.

I'm pretty proud of this one! Rather than place a bandaid, I did some refactoring that I think makes for an overall cleaner rollAttack() function :)

Why did I only minimally touch rollDamage()? I can't figure out where this function is actually used. I think it's used nowhere? It will be useful for enhancements such as #332 so I left it in place for now.

### CODE REVIEW

File: src/module/actor/entity.js [hunk 1]
```diff
@@ -437,49 +437,61 @@ export default class OseActor extends Actor {
...
+    if (ascending && data.thac0.bba) {
+      rollParts.push(data.thac0.bba);
     }
+    // for each type of attack, add the Tweaks bonus
+    // and str/dex modifier only if it's non-zero
     if (options.type === "missile") {
       rollParts.push(
-        data.scores.dex.mod.toString(),
-        data.thac0.mod.missile.toString()
+        ...[data.scores.dex.mod, data.thac0.mod.missile].reduce((a, b) => {
```
Comment (wyrmisis) [inline src/module/actor/entity.js:470]: ⛳ 
```js
let attackMods = [];

if (options.type === 'missile')
  attackMods = [data.scores.dex.mod, data.thac0.mod.missile]
else if (options.type === 'melee')
  attackMods = [data.scores.str.mod, data.thac0.mod.melee];
  
rollParts.push(...attackMods.reduce((a, b) => (!b ? a : [...a, b]), []);
```

File: src/module/actor/entity.js [hunk 2]
```diff
@@ -437,49 +437,50 @@ export default class OseActor extends Actor {
...
+      : game.i18n.format("OSE.roll.attacks", {
+          name: this.name,
+        });
+
+    const dmgParts = [
+      // Weapon damage roll value
+      attData.item?.system?.damage ?? "1d6",
+      // Weapon damage bonus
+      attData.item?.system?.bonus,
+    ].reduce((acc, curr) => {
```
Comment (wyrmisis) [inline src/module/actor/entity.js:453]: The reducer here is the same as what's on line 475. We could make that an arrow function constant so we only have to write it once.

**Comment by anthonyronda** [comment]
The arrow function is at the top because that's where ESLint told me to put it
The huge JSDoc is there because I wanted to write a comment for the out-of-context arrow function... then made it a JSDoc... then felt I needed one for the original method I was refactoring...

File: src/module/actor/entity.js [hunk 3]
```diff
@@ -434,52 +442,62 @@ export default class OseActor extends Actor {
...
-      );
-    }
-    if (attData.item && attData.item.system.bonus) {
-      rollParts.push(attData.item.system.bonus);
-    }
-    const thac0 = data.thac0.value;
-    if (options.type === "melee") {
-      dmgParts.push(data.scores.str.mod);
+
+    if (ascending && data.thac0.bba) {
```
Comment (wyrmisis) [inline src/module/actor/entity.js:480]: Since the if/else at line 487 doesn't use curlies, should we remove them here, since we're not doing multiple things in this if block?

Comment (anthonyronda) [reply src/module/actor/entity.js:480]: hmmm can I promise to catch it in the #387 PR?

Comment (wyrmisis) [reply src/module/actor/entity.js:480]: Hahaha fine, I'll stop nitpicking. :P

**Review by wyrmisis — APPROVED** [review]
Clean enough to eat off of. 🚢

File: src/module/actor/entity.js (hunk 3 above)
Comment (anthonyronda) [reply src/module/actor/entity.js:480]: this is not likely the only place where we do this, so I think we'll need to enable an optional linting rule
