### PR TITLE
fix: Read and delete treasure tables on Monster sheets

### LINKED ISSUE #226: Dropping a rolltable onto 'Treasure Type' on the monster sheet is broken
### What happened?

1. Create a new monster
2. Drop any rolltable onto the 'Treasure Type' field

Result: The field shows a broken link to an undefined rolltable

### What is the expected behaviour?

A link to rolltable just dropped.

### Relevant Errors and Warnings

_No response_

### Additional Support Details

_No response_

### Foundry VTT Core Version

V10

### Old-School Essentials Core Version

1.6.3

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #227: Make the 'Treasure type' field on the monster sheet deletable
### New Feature or Changed Behaviour

Add a method to delete the content of the 'Treasure type' field on the monster sheet.

### Why?

Right now the only way to get rid of the content of the 'Treasure type' field is to export the monster, edit the JSON file and reimport it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by wyrmisis**
This changeset allows users to delete a monster's treasure rolltable by right clicking on it. It also allows monster treasure tables to successfully get added to the monster.

**Note**: I'd appreciate if someone familiar with maintaining v9 compatibility could have a look at this; I've been so buried in v10 work these days that I've lost track of what works in v9 vs. v10 :)

Fixes #226
Fixes #227

### CODE REVIEW

File: src/module/actor/monster-sheet.js [hunk 1]
```diff
@@ -224,7 +225,7 @@ export class OseActorSheetMonster extends OseActorSheet {
         .index.filter((el) => el._id === data.id);
       link = `@Compendium[${data.pack}.${data.id}]{${tableData[0].name}}`;
     } else {
-      link = `@RollTable[${data.id}]`;
+      link = `@UUID[${data.uuid}]`;
```
Comment (wyrmisis) [inline src/module/actor/monster-sheet.js:228]: Can anyone tell me if this works in v9?

Comment (anthonyronda) [reply src/module/actor/monster-sheet.js:228]: this is a V10 breaking change

https://foundryvtt.com/article/v10-text-editor/#uuidLinks
image

Comment (anthonyronda) [reply src/module/actor/monster-sheet.js:228]: thanks for noting it specifically. This will go on the pile of things earmarked "would need to be changed if V9 backwards compatibility once again becomes a priority"

File: src/module/actor/monster-sheet.js [hunk 2]
```diff
@@ -303,6 +304,13 @@ export class OseActorSheetMonster extends OseActorSheet {
       actorObject.rollAppearing({ event: ev, check: check });
     });
 
+    html.find(".treasure-table a").contextmenu((ev) => {
```
Comment (anthonyronda) [inline src/module/actor/monster-sheet.js:307]: Cool! A novel solution for removing the treasure table here. At some point we'll revisit if we can add a "are you sure" because I imagine an accidental right click would be really annoying

File: src/module/actor/monster-sheet.js (hunk 1 above)
Comment (wyrmisis) [reply src/module/actor/monster-sheet.js:228]: Sure thing. I can change this to use the line I'm removing if the user's on v9, and the line I'm adding if the user's on v10, if we like.

Comment (anthonyronda) [reply src/module/actor/monster-sheet.js:228]: While plenty of the codebase attempts V9-10 cross-compatibility, we are still overall pretty far away from achieving it. I'm planning to accept this PR as-is :)

**Review by anthonyronda — APPROVED** [review]
LGTM
