### PR TITLE
fix(dice): Dice rolling fixes for 1.8.x

### LINKED ISSUE #333: Attack Fails with No Target
### What happened?

1. Create an actor with a weapon
2. Roll attacks with no target.
3. If the attack is 1 or less the attack fails.

### What is the expected behaviour?

The attack roll should always occur regardless of the roll result to hit if there is not a target. The only possible exception would be a 1, which RAW always misses. I propose that this still result in a damage roll with no target, as there is no alternative way for the GM/Players to create a weapon damage roll in chat without a to hit roll preceding it.

### Relevant Errors and Warnings

```shell
N/A
```

### Additional Support Details

_No response_

### Foundry VTT Core Version

V10

### Old-School Essentials Core Version

1.7.5

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #340: Rolls totalling 1 auto-fail, and rolls totalling 20+ auto-succeed, when it should only be "natural 1s and 20s"
### What happened?

1. Roll a to-hit `1d20` with a natural result of 2 against an AAC of 1
2. Modify the result by -1 (1 vs AAC 1)
3. The roll fails

Also

1. Roll a to-hit `1d20` with a natural result of 19 against an AAC of 21
2. Modify the result by +1 (20 vs AAC 21)
3. The roll succeeds

### What is the expected behaviour?

Attack rolls with a modified result of 1 are allowed to succeed if it hits the target armor class, and rolls with a modified result of 20 are allowed to fail if it misses the target armor class

### Relevant Errors and Warnings

_No response_

### Additional Support Details

_No response_

### Foundry VTT Core Version

V10

### Old-School Essentials Core Version

1.7.5

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #341: In ascending AC only, natural 1s can succeed and natural 20s can fail
### What happened?

With AAC enabled:

1. Make a weapon with bonus "+20"
2. Roll a natural 1 with no target
3. The attack succeeds

Also
1. Make a weapon with bonus "-20"
2. Roll a natural 20 with no target
3. The attack fails

### What is the expected behaviour?

From RAW: 1s and 20s

"Natural 20 attack rolls always hit. Natural 1 attack rolls always miss."

### Relevant Errors and Warnings

_No response_

### Additional Support Details

_No response_

### Foundry VTT Core Version

V10

### Old-School Essentials Core Version

1.7.5

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bakbakbakbakbak**
resolves #341, resolves #340, resolves #333

- Reworked tests for dice
  - Moved `createMockData` and `createMockAttackData` into tests as they were only used there
  - Updated  `createMockRoll` to properly mock a roll as needed by tests
  - Rewrote the tests for `attackIsSuccess` to better explain functionality
  - Rewrote `digestAttackResult` tests
    - Updated `createMockRoll` calls
    - #340 : Added tests for these cases
    - Reformulated `createMockRoll` calls to calculate values instead of using hard-coded values.
      - Calculations include calculating attack bonus from thac0 score.
  - Rewrote `sendAttackRoll` tests
    - Removed majority of tests that were just checking the chat messages for content
    - Updated the mocking data to more accurately represent actual data from weapon rolling
- Dice helper
  - Fixed `digestResult`
    - Added description
    - Didn't use proper value for `die`
  - Reworked `attackIsSuccess` to make it more understandable. 
    - Added description
    - To use it will take:
      - `roll, target, bonus` for Ascending AC
      - `roll, thac0, ac` for Descending AC
    - Linted the last `if return` statement.
    - #342: Incorporates the changes in said PR.
  - Rewrote `digestAttackResult`
    - Added description
    - #333 : Updated default AC and AAC values to always allow to hit target unless target is selected (except for natural 1s).
    - #341 : Rewrote logic to support Ascending AC & Descending AC utilizing `attackIsSuccess`
    - Properly flags when an Ascending AC roll fails (previously didn't set `result.isFailure`)
  - Added description for `sendAttackRoll`

### CODE REVIEW

**Comment by bakbakbakbakbak** [comment]
Marking this as draft until it solves #340 too. Looking into this tomorrow.

File: src/module/helpers-dice.js [hunk 1]
```diff
@@ -82,23 +82,32 @@ const OseDice = {
...
+    // eslint-disable-next-line default-case
     switch (data.roll.type) {
       case "result": {
         if (roll.total === result.target) {
           result.isSuccess = true;
         } else {
           result.isFailure = true;
         }
-
+
```
Comment (bakbakbakbakbak) [inline src/module/helpers-dice.js:110]: cleanup

File: src/module/helpers-dice.js [hunk 2]
```diff
@@ -176,44 +202,65 @@ const OseDice = {
     result.target = data.roll.thac0;
     const targetActorData = data.roll.target?.actor?.system || null;
 
-    const targetAc = data.roll.target ? targetActorData.ac.value : 9;
-    const targetAac = data.roll.target ? targetActorData.aac.value : 10;
+    const targetAc = data.roll.target ? targetActorData.ac.value : 20;
+    const targetAac = data.roll.target ? targetActorData.aac.value : -20;
```
Comment (anthonyronda) [inline src/module/helpers-dice.js:206]: As I noted in #332 I think this is fine and good for now but doesn't resolve the ultimate UI concern of providing a common sense flow for "no target" combat. We still might as well accept this change as-is because we don't have an enhancement change ready, but I'll be looking forward to designing a new flow in accordance with #332 in the future

File: src/module/helpers-dice.js [hunk 3]
```diff
@@ -176,44 +202,65 @@ const OseDice = {
...
+    } else {
+      result.details = game.i18n.format("OSE.messages.AttackFailure", {
+        bonus: result.target,
+      });
+      result.isFailure = true;
     }
     return result;
   },
 
+  // eslint-disable-next-line jsdoc/require-param
```
Comment (anthonyronda) [inline src/module/helpers-dice.js:245]: was this included in an earlier commit and not taken out after including the params in a later commit? Or does this JSDoc comment block somehow not fulfill this rule?

File: src/module/helpers-dice.js (hunk 2 above)
Comment (bakbakbakbakbak) [reply src/module/helpers-dice.js:206]: I agree.

File: src/module/__tests__/helpers-dice.test.ts [hunk 4]
```diff
@@ -372,7 +477,6 @@ export default ({
       rollData.data.roll.dmg = [];
       await OseDice.sendAttackRoll(rollData);
       await waitForInput();
-      await waitForInput();
```
[the remark this answers is not in the document]
Comment (bakbakbakbakbak) [reply src/module/__tests__/helpers-dice.test.ts:375]: Looking at the test, I'm not sure why I put multiple `waitForInput` here. I removed the multiples and tried running it, and it looks like the tests are just volatile due to timing, which makes sense. This is most likely why I put multiple `waitForInput` before, due to lag.

There might be an idea to rework the tests, to become more deterministic, especially since a lot of them waits for dice rolls, chat card rendering, and sheet rendering.

I'm not really sure what is the appropriate course of action here. I'll spend some time thinking about how to get to the problem.

File: src/module/helpers-dice.js (hunk 3 above)
Comment (bakbakbakbakbak) [reply src/module/helpers-dice.js:245]: I couldn't figure it out last time I looked at it, because `param0.speaker` is clearly there. However... There is a missing whitespace between `speaker` and `-`... Fixing that now.

File: src/module/__tests__/helpers-dice.test.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (anthonyronda) [reply src/module/__tests__/helpers-dice.test.ts:375]: Hmmm, is it ok if I just merge and we'll make a ticket for deterministic waitforinput?

[the remark this answers is not in the document]
Comment (bakbakbakbakbak) [reply src/module/__tests__/helpers-dice.test.ts:375]: I would be OK with that, it may be better to have the tests with the potential volatility compared to waiting until this is figured out.

**Review by anthonyronda — APPROVED** [review]
LGTM
